# -*- coding: utf-8 -*-

dict_veri_katmani = {
    'objectid'                              : 0,
    'ek_2'                                  : 1,
    'katman_adi'                            : 2,
    'katman_durumu'                         : 3,
    'tucbs_uygunluk'                        : 4,
    'veri_turu'                             : 8,
    'veri_tipi'                             : 9,
    'veri_adedi'                            : 10,
    'veri_formati'                          : 11,
    'projeksiyon'                           : 62,
    'datum'                                 : 63,
    'olcek_duzey'                           : 13,
    'veri_guncelleme_periyod'               : 20,
    'son_veri_guncelleme_tarih'             : 21,
    'veri_envanteri_aciklama'               : 49,
    'tucbs_katmani'                         : 53,
    'inspire_katmani'                       : 54,    
    'katman_aciklama'                       : 61,
    'tucbs_tema_harici'                     : 5,
    'inspire_uygunluk'                      : 6,
    'tesim_alindi'                          : 14,
    'teslim_formati'                        : 15,
    'teslim_alinan_veri_sayisi'             : 16,
    'vk_amac'                               : 24,
    'vk_kullanim'                           : 25,
    'vk_kokeni'                             : 26,
    'vk_copleteness_fazlalik'               : 23,
    'vk_fazlalik_yeni'                      : 70,
    'vk_eksizlik_yeni'                      : 64,
    'vk_lc_kavramsal_tutarlilik'            : 27,
    'vk_kavramsal_yeni'                     : 71,
    'vk_tanim_kumesi_yeni'                  : 72,
    'vk_format_tutarlilik_yeni'             : 73,
    'vk_topoloji_tutarlilik_yeni'           : 74,
    'vk_pa_mutlak_dogruluk'                 : 28,
    'vk_konumsal_mutlak_dogruluk_yeni'      :75
}